name: 'Scan github action'
description: 'A github action to scan repositories Dockerfile'
inputs:
  GH_TOKEN:
    description: 'A Github PAT'
    required: true
  TESTE:
    required: false
    default: TTTTTTTT

outputs:
  SEMGREP_CHECK:
    description: 'check of sempgre'
    value: ${{ steps.executing_action.outputs.SEMGREP_CHECK }}
  SEMGREP_SECRET_CONFIG:
    description: 'check of trivy SCA secret'
    value: ${{ steps.executing_action.outputs.SEMGREP_SECRET_CONFIG }}
  GITLEAKS_CHECK:
    description: 'check of gitleaks'
    value: ${{ steps.executing_action.outputs.GITLEAKS_CHECK }}
  GITLEAKS_SECRET_CONFIG:
    description: 'check of trivy SCA secret'
    value: ${{ steps.executing_action.outputs.GITLEAKS_SECRET_CONFIG }}
  TRIVY_SECRET_CHECK:
    description: 'check of trivy secret'
    value: ${{ steps.executing_action.outputs.TRIVY_SECRET_CHECK }}
  TRIVY_SECRET_THRESHOLD:
    description: 'check of trivy SCA secret'
    value: ${{ steps.executing_action.outputs.TRIVY_SECRET_THRESHOLD }}

runs:
  using: "composite"
  steps:
    - run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash
      name: Installing dependencies
    - name: Test of inputs
      run: |
        echo "Default value ${{ inputs.TESTE.default }}"
    - name: Executing action
      id: executing_action
      run: | 
        export GH_TOKEN=${{ inputs.GH_TOKEN }}
        python $GITHUB_ACTION_PATH/src/main.py
      shell: bash
